run_name: 'SE3-joint-fullAtom'
logdir: '/path/to/logdir'
wandb_params:
  mode: 'online'  # disabled, offline, online
  entity: 'my_username'
  group: 'bindingmoad'
dataset: 'bindingmoad'
datadir: '/path/to//processed_noH_full/'
enable_progress_bar: False
num_sanity_val_steps: 0

mode: 'joint'
pocket_representation: 'full-atom'
virtual_nodes: False
batch_size: 16
lr: 5.0e-4
n_epochs: 1000
num_workers: 2
gpus: 2
clip_grad: True
augment_rotation: False
augment_noise: 0

auxiliary_loss: False
loss_params:
  max_weight: 0.001
  schedule: 'linear'
  clamp_lj: 3.0

egnn_params:
  device: 'cuda'
  edge_cutoff_ligand: null
  edge_cutoff_pocket: 0.8  # = 4.0 / 5.0
  edge_cutoff_interaction: 1.4  # = 7.0 / 5.0
  reflection_equivariant: False
  edge_embedding_dim: 8
  joint_nf: 128
  hidden_nf: 192
  n_layers: 6
  attention: True
  tanh: True
  norm_constant: 1
  inv_sublayers: 1
  sin_embedding: False
  aggregation_method: 'sum'
  normalization_factor: 100  # used if aggregation_method='sum'

diffusion_params:
  diffusion_steps: 500
  diffusion_noise_schedule: 'polynomial_2'  # learned, cosine
  diffusion_noise_precision: 1.0e-5
  diffusion_loss_type: 'l2'  # vlb, l2
  normalize_factors: [5, 5]  # [x, h]

eval_epochs: 25
visualize_sample_epoch: 25
visualize_chain_epoch: 25
eval_params:
  n_eval_samples: 100
  eval_batch_size: 50
  smiles_file: '/path/to/train_smiles.npy'
  n_visualize_samples: 5
  keep_frames: 100